export default class DummyData{
    static data = [
        {
        "PANO": 7,
        "ConstituencyName": "Aldershot",
        "ConstituencyID": "E14000530",
        "ConstituencyType": "Borough",
        "Electorate": 72430,
        "ValidVotes": 46191,
        "field7": "",
        "RegionID": "E12000008",
        "County": "Hampshire",
        "Region": "South East",
        "Country": "England"
        },
        {
        "PANO": 8,
        "ConstituencyName": "Aldridge-Brownhills",
        "ConstituencyID": "E14000531",
        "ConstituencyType": "Borough",
        "Electorate": 60215,
        "ValidVotes": 39497,
        "field7": "",
        "RegionID": "E12000005",
        "County": "West Midlands",
        "Region": "West Midlands",
        "Country": "England"
        },
        {
        "PANO": 9,
        "ConstituencyName": "Altrincham and Sale West",
        "ConstituencyID": "E14000532",
        "ConstituencyType": "Borough",
        "Electorate": 71511,
        "ValidVotes": 50517,
        "field7": "",
        "RegionID": "E12000002",
        "County": "Greater Manchester",
        "Region": "North West",
        "Country": "England"
        },
        {
        "PANO": 11,
        "ConstituencyName": "Amber Valley",
        "ConstituencyID": "E14000533",
        "ConstituencyType": "County",
        "Electorate": 69510,
        "ValidVotes": 45717,
        "field7": "",
        "RegionID": "E12000004",
        "County": "Derbyshire",
        "Region": "East Midlands",
        "Country": "England"
        },
        {
        "PANO": 18,
        "ConstituencyName": "Arundel and South Downs",
        "ConstituencyID": "E14000534",
        "ConstituencyType": "County",
        "Electorate": 77242,
        "ValidVotes": 56477,
        "field7": "",
        "RegionID": "E12000008",
        "County": "West Sussex",
        "Region": "South East",
        "Country": "England"
        },
        {
        "PANO": 19,
        "ConstituencyName": "Ashfield",
        "ConstituencyID": "E14000535",
        "ConstituencyType": "County",
        "Electorate": 77091,
        "ValidVotes": 47409,
        "field7": "",
        "RegionID": "E12000004",
        "County": "Nottinghamshire",
        "Region": "East Midlands",
        "Country": "England"
        },
        {
        "PANO": 20,
        "ConstituencyName": "Ashford",
        "ConstituencyID": "E14000536",
        "ConstituencyType": "County",
        "Electorate": 85177,
        "ValidVotes": 57372,
        "field7": "",
        "RegionID": "E12000008",
        "County": "Kent",
        "Region": "South East",
        "Country": "England"
        },
        {
        "PANO": 21,
        "ConstituencyName": "Ashton-under-Lyne",
        "ConstituencyID": "E14000537",
        "ConstituencyType": "Borough",
        "Electorate": 68343,
        "ValidVotes": 38918,
        "field7": "",
        "RegionID": "E12000002",
        "County": "Greater Manchester",
        "Region": "North West",
        "Country": "England"
        },
        {
        "PANO": 22,
        "ConstituencyName": "Aylesbury",
        "ConstituencyID": "E14000538",
        "ConstituencyType": "County",
        "Electorate": 80315,
        "ValidVotes": 55419,
        "field7": "",
        "RegionID": "E12000008",
        "County": "Buckinghamshire",
        "Region": "South East",
        "Country": "England"
        },
        {
        "PANO": 26,
        "ConstituencyName": "Banbury",
        "ConstituencyID": "E14000539",
        "ConstituencyType": "County",
        "Electorate": 86420,
        "ValidVotes": 58008,
        "field7": "",
        "RegionID": "E12000008",
        "County": "Oxfordshire",
        "Region": "South East",
        "Country": "England"
        },
        {
        "PANO": 28,
        "ConstituencyName": "Barking",
        "ConstituencyID": "E14000540",
        "ConstituencyType": "Borough",
        "Electorate": 73977,
        "ValidVotes": 43041,
        "field7": "",
        "RegionID": "E12000007",
        "County": "London",
        "Region": "London",
        "Country": "England"
        },
        {
        "PANO": 29,
        "ConstituencyName": "Barnsley Central",
        "ConstituencyID": "E14000541",
        "ConstituencyType": "Borough",
        "Electorate": 64534,
        "ValidVotes": 36560,
        "field7": "",
        "RegionID": "E12000003",
        "County": "South Yorkshire",
        "Region": "Yorkshire and The Humber",
        "Country": "England"
        },
        {
        "PANO": 30,
        "ConstituencyName": "Barnsley East",
        "ConstituencyID": "E14000542",
        "ConstituencyType": "County",
        "Electorate": 69135,
        "ValidVotes": 38517,
        "field7": "",
        "RegionID": "E12000003",
        "County": "South Yorkshire",
        "Region": "Yorkshire and The Humber",
        "Country": "England"
        },
        {
        "PANO": 31,
        "ConstituencyName": "Barrow and Furness",
        "ConstituencyID": "E14000543",
        "ConstituencyType": "County",
        "Electorate": 68338,
        "ValidVotes": 43275,
        "field7": "",
        "RegionID": "E12000002",
        "County": "Cumbria",
        "Region": "North West",
        "Country": "England"
        },
        {
        "PANO": 32,
        "ConstituencyName": "Basildon and Billericay",
        "ConstituencyID": "E14000544",
        "ConstituencyType": "Borough",
        "Electorate": 66347,
        "ValidVotes": 43028,
        "field7": "",
        "RegionID": "E12000006",
        "County": "Essex",
        "Region": "East",
        "Country": "England"
        }
    ]
}


